### ISSUE TITLE
Yoga cannot find Project not found: 'AbisStarterkit$dev' after connecting to prisma

### ISSUE THREAD

**Issue by QAY** [DBIAnalytics/ABIS-OS-Beta#13]
Check the whole log [HERE](https://gitlab.com/dbianalytics/abis-os-beta/-/jobs/479879063)
Error by Yoga service:

(node:7) UnhandledPromiseRejectionWarning:   Error: Project not found: 'AbisStarterkit$dev'
--
at BatchedGraphQLClient.<anonymous>   (/usr/yoga/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:69:35)
at step   (/usr/yoga/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
at Object.next   (/usr/yoga/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
at fulfilled   (/usr/yoga/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
at processTicksAndRejections   (internal/process/task_queues.js:97:5)
(node:7) UnhandledPromiseRejectionWarning:   Unhandled promise rejection. This error originated either by throwing inside   of an async function without a catch block, or by rejecting a promise which   was not handled with .catch(). To terminate the node process on unhandled   promise rejection, use the CLI flag `--unhandled-rejections=strict` (see   https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection   id: 1)
(node:7) [DEP0018] DeprecationWarning:   Unhandled promise rejections are deprecated. In the future, promise   rejections that are not handled will terminate the Node.js process with a   non-zero exit code.

**Comment by jaensen** [comment]
it looks like a "prisma deploy" is missing or not executed properly.
I tried not to break anything in your build scripts but a few things changed nonetheless.

**Comment by smart-health-ops** [comment]
prisma deploy is existent in Dockerfile of Prisma. See last command at the end. If it were not existent, prisma container would not be reachable. Prisma might not setup the project in a proper way due to the database exception, which says that prisma database is not existent. prisma should normally catch this exception and create the non-existent database. On the local machine it works fine.

Dockerfile for prisma without commented lines:

FROM gdhami/prisma-1.34-cli
WORKDIR /usr/prisma/
COPY . .
COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh
CMD ["sh", "-c", "./wait-for-it.sh" , "db:5432" , "--strict" , "--timeout=300" , "--" , "prisma", "deploy"]
